In [3]:
# numpy exercises
'''
This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`
'''
import numpy as np

In [5]:
#### 2. Create a null vector of size 10 (★☆☆)
#`hint: np.zeros`
vector0 = np.zeros(10)
vector0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#`hint: array[4]`
vector01 = np.array([int(x==4) for x in range(10)])
vector01

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [20]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
#`hint: arange`
v_rang = np.arange(10,50)
v_rang

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [30]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
#`hint: reshape`
mat_3 = np.arange(0,9).reshape((3,3))
mat_3


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
#`hint: np.nonzero`
x = [1,2,0,0,4,0]
v_nonzero = np.nonzero(x)
v_nonzero


(array([0, 1, 4], dtype=int64),)

In [38]:
#### 7. Create a 3x3 identity matrix (★☆☆)
#`hint: np.eye`
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
#`hint: np.random.random`
np.random.random((3,3,3))


array([[[0.76967706, 0.8023667 , 0.54472672],
        [0.94217555, 0.0451306 , 0.2117003 ],
        [0.9746269 , 0.17461162, 0.40911897]],

       [[0.67825525, 0.21537099, 0.53744679],
        [0.00108752, 0.1045223 , 0.79110505],
        [0.14943634, 0.5268795 , 0.3239753 ]],

       [[0.35246666, 0.00254355, 0.82390728],
        [0.56195771, 0.60103548, 0.91152371],
        [0.37911199, 0.74767541, 0.72359126]]])

In [49]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
#`hint: min, max`
a = np.random.random((10,10))
#print(a)
amin, amax = a.min(), a.max() 
print( amin,amax)

0.01061178968147447 0.9952432785810379


In [52]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
#`hint: mean`
b = np.random.random(30)
b_mean = np.mean(b)
b_mean

0.5333588318351343

In [76]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
#`hint: np.diag` # extract or contruct a diagonal array
#numpy.diag(v, k=0) , v = array_like , k = int, optional, diagonal in question, default is 0
D = np.diag(1+np.arange(4), k =-1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [80]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
#`hint: (x -mean)/std`
#means to scale the values such that that the range of the row 
# or column values is between 0 and 1
E = np.random.random((5,5))
norm_E = (E - np.mean(E)) / np.std(E)
norm_E


array([[ 1.33144693, -1.06436241,  0.51459275,  1.71644483, -1.5478296 ],
       [-0.68478117,  0.95689792,  0.65712332, -0.3811362 ,  0.44837881],
       [ 1.36973362, -0.37777997, -0.22060922, -1.86592563,  0.10932848],
       [-0.00460458, -1.60288732, -0.73862576, -0.27845134, -1.02677589],
       [ 1.4126747 , -0.07073388, -0.06073753, -0.16765487,  1.576274  ]])

In [89]:
#### 13. How to find common values between two arrays? (★☆☆)
#`hint: np.intersect1d`
A1 = np.random.random(5)
A2 = np.random.random(5)

#intersect_A1A2 = np.intersect1d(A1,A2)
print(A1)
print(A2)
print(np.intersect1d(A1,A2))

[0.31861474 0.14299734 0.60441123 0.30804358 0.93301771]
[0.32348288 0.58960986 0.21517986 0.45373495 0.71488732]
[]


In [90]:
B1 = [1,5,3,6,9]
B2 = [5,8,8,9,3]

print(B1)
print(B2)
print(np.intersect1d(B1,B2))

[1, 5, 3, 6, 9]
[5, 8, 8, 9, 3]
[3 5 9]


In [103]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
#`hint: sort`
C = np.random.random(10)

print('Matrix non sorted')
print(C)

#  sorting the list in ascending order
C.sort()

print('Sorted matrix')
print(C)

Matrix non sorted
[0.52347821 0.46194652 0.83368548 0.14320015 0.79127115 0.18737621
 0.12991187 0.78697818 0.2368926  0.91109689]
Sorted matrix
[0.12991187 0.14320015 0.18737621 0.2368926  0.46194652 0.52347821
 0.78697818 0.79127115 0.83368548 0.91109689]


In [108]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#`hint: argmax`
D = np.random.random(10)
print("Original array:")

print(D)

print("Maximum value replaced by 0:")

D[D.argmax()] = 0
print(D)



Original array:
[0.90592763 0.93863677 0.34982839 0.63665463 0.53690115 0.80178938
 0.42799638 0.78545172 0.65246438 0.1560409 ]
Maximum value replaced by 0:
[0.90592763 0.         0.34982839 0.63665463 0.53690115 0.80178938
 0.42799638 0.78545172 0.65246438 0.1560409 ]


In [118]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
#`hint: mean(axis=,keepdims=)`
F = np.random.random((3,3))

print('Original matrix')
print(F)

print('Mean of each row of the matrix')
print(F.mean(axis = 1, keepdims = True))

print('Substraction between the original matrix and the mean')
F_substract = F - F.mean(axis = 1, keepdims = True)
print(F_substract)

Original matrix
[[0.11412697 0.68542628 0.59051383]
 [0.81111102 0.00114519 0.2638728 ]
 [0.78118165 0.1873305  0.73299717]]
Mean of each row of the matrix
[[0.46335569]
 [0.35870967]
 [0.56716977]]
Substraction between the original matrix and the mean
[[-0.34922872  0.22207059  0.12715813]
 [ 0.45240135 -0.35756448 -0.09483687]
 [ 0.21401188 -0.37983927  0.16582739]]


In [124]:
#### 17. How to get the n largest values of an array (★★★)
Z = np.arange(10000)

#Shuffle a list (reorganize the order of the list items)
np.random.shuffle(Z)
n = 5

#slow way, np.argsort() is to sort an array
sorted_index_array = np.argsort(Z)

# sorted array
sorted_array = Z[sorted_index_array]
print("Sorted array:", sorted_array)

# we want n=5 largest value (see above)
# we are using negative indexing concept  
# take n largest value
rslt = sorted_array[-n : ]

# show the output
print("{} largest value:".format(n),
      rslt)
#print(Z[np.argsort(Z)/np.argpartition`


Sorted array: [   0    1    2 ... 9997 9998 9999]
5 largest value: [9995 9996 9997 9998 9999]


In [125]:

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
#`hint: np.where`
Y = np.arange(0,15).reshape(5,3)
print(Y)
print("Replacing of items or squaring which are larger than 4")
Y = np.where(Y <= 5, Y, Y**2)
Y

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Replacing of items or squaring which are larger than 4


array([[  0,   1,   2],
       [  3,   4,   5],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196]])

In [1]:
my_list = [ 1, 2, 3]

list( map( lambda x: x**2, my_list ) ) 

[1, 4, 9]

In [2]:
my_list = [1,2,3]
yout_list = [4,5,6]
l=[]
for n in my_list:
    l.append(n**2)

In [3]:
l

[1, 4, 9]

In [ ]:
def sqr(x): 
    return x**2
    

In [ ]:
def mult(x): 
    return x*y

In [ ]:
mult(2,3)

In [ ]:
l = list(map(mult, my_list, your_list))

In [ ]:
l